### ISSUE TITLE
Locale passing issue with ethplorer

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#162] opened 2017-10-18 17:43 UTC
I have a currency on a Wallet address where the `.` in the token's value is appearing as a `,`. 

The value of **xx.xx** is appearing as **xx,xx0.0**.

Discovered in v0.9.4. If it's any help - this is my Language and Region settings in System Preferences. This issue is happening only appears with one ether-based currency.

<img width="532" alt="screen shot 2017-10-18 at 18 40 41" src="https://user-images.githubusercontent.com/2099705/31733596-040ffa48-b434-11e7-881b-492be46c8855.png">

**Comment by wolffan** [comment] 2017-10-23 09:40
@cjdowner if I do what you did all currencies go crazy...

**Comment by wolffan** [comment] 2017-10-23 09:55
Also @cjdowner I can't reproduce... if I change the system preferences, I get the right conversion 0.00 or X,XXX.xx
Can you double check again please? also changing system config meands you need to close and open the app again I think for effects to be taken

**Comment by cjdowner** [comment] 2017-10-23 10:00
Note: I am not changing the number separator preference. I was simply stating what my default is for the British locale (as I'm aware it is different to the rest of Europe).

To help clarify, I'm seeing a currency in Balance at 1000* its value when I view it on My Ether Wallet. This is because Balance is displaying at `,` when it should be a `.`.

**Comment by wolffan** [comment] 2017-10-23 10:37
You mean that I have some milions in GBP now @cjdowner...? Almost wish this was real (looking at it now)

<img width="384" alt="screen shot 2017-10-23 at 12 36 42" src="https://user-images.githubusercontent.com/1092080/31884869-e3070576-b7ee-11e7-91cc-d85e0dc1366d.png">

**Comment by wolffan** [comment] 2017-10-23 13:51
On a more elaborated note @cjdowner before the locale was forced to US always.
Seems with the new changes something happened, the locales are all over the place (I downloaded the last beta and works fine).

@einsteinx2 what changes where introduced with the skinning and the conversion function? Because it may be related...

**Comment by wolffan** [comment] 2017-10-24 15:39
Should be sorted, could you give feedback when the branch is merged @cjdowner ? https://github.com/balancemymoney/balance-open/pull/176

**Closed** 2017-10-25 09:25 UTC
Labels: bug
