### ISSUE TITLE
Improve converted price accuracy

### ISSUE THREAD

**Issue by christianbaroni** [balancemymoney/balance-open#385] opened 2017-12-15 19:40 UTC
1. MetaMask address added to Balance with balance of 200 ZRX tokens
2. Sent an additional 100 ZRX tokens to MetaMask address
3. Updated balance (300 ZRX) shown in MetaMask and on Etherscan, but not updated in Balance
4. Deleted MetaMask address from Balance and added again, and correct balance is now shown

Prices were also inaccurate until I deleted the account and readded it.

Note: account was originally added in an older version of Balance.

**Comment by christianbaroni** [comment] 2017-12-15 19:42
On both Mac and iOS.

**Comment by christianbaroni** [comment] 2017-12-18 01:15
Also, noticed today that the value of my KNC tokens (Kyber Network) and their price hasn't changed in Balance for over a day. They're worth about $2.23 each but Balance is showing a price of $1.61, far lower than any exchange.

0x price also seems to be inaccurate, maybe others as well.

**Comment by wolffan** [comment] 2017-12-21 08:57
Prices on wallets are taken from our service for now, I can revisit it, but I think I've looked at it after this was open.
If no price we fail back to our own average.
Price is unlikely to be the same on different exchanges as well :)

**Comment by einsteinx2** [comment] 2017-12-22 20:37
Regarding your first issue, I have a similar problem on my iOS app. I think something happened when I switched keychain implementations. It was supposed to be seamless but it seems that it can't find my old keychain data (at least on iOS where I added stuff a while ago). On my Mac, it seemed to be able to read my keychain info no problem... Also it is certainly reading my database password from the keychain, so I don't know what's up, but I don't think the original issue still exists. It's a beta thing, just re-adding the accounts fixes it and seems to stay up to date now.

**Comment by einsteinx2** [comment] 2017-12-22 20:40
@christianbaroni as Raimon said, we use the price ticker price now for wallets (which is a price average across exchanges). It's possible one exchange had it much lower than the others. In the future, we'd like to have an option to choose preferred exchanges for pricing so that we only average the exchanges you actually use.

The problem is the prices are so volatile, even one exchange will go up or down by 20% or more in just an hour, and they don't all follow each other, so exchanges frequently have very different prices.

The core problem is essentially that there is no one price for any crypto. And to make it worse, for tokens, they are only tradable for bitcoin or ether usually, not USD, so we first convert to one of those then to fiat, so there's even more room for averaging to cause prices that look off. Especially with less popular or lower volume tokens.

This is something we'll need to continue to improve through the 1.0.x releases.

**Comment by einsteinx2** [comment] 2017-12-22 20:41
Even sites like coinmarketcap are frequently "wrong" with their prices because they also aggregate, and if there's fast movement on your exchange of choice or just in general, the prices can be even thousands of dollars off for coins like bitcoin.

I think we've got it as good as we can for 1.0, and we'll keep iterating. Moving this to 1.0.1.

**Comment by einsteinx2** [comment] 2018-01-15 17:10
The main way that we have left to improve this I think is to allow the user to choose preferred exchanges. For example, I always sell my crypto for fiat using Coinbase so I want to use their fiat price, and I generally trade coins on Binance, so I want to prioritize their price for tokens. These kind of customizations should allow for more accurate (to that person) prices.

**Comment by wolffan** [comment] 2018-01-18 09:05
@einsteinx2 I'll drop this one to do the exchange preference?

**Closed by wolffan** 2018-01-18 09:05 UTC
Labels: 0 - Backlog, bug
