### ISSUE TITLE
Amounts in Balance iOS and Coinbase don’t match

### ISSUE THREAD

**Issue by kristinatauch** [balancemymoney/balance-open#295] opened 2017-11-17 10:28 UTC
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pedrouid** [comment] 2017-11-17 11:13
![23667177_162008401202565_1326165497_n](https://user-images.githubusercontent.com/10136079/32944677-44d2df62-cb88-11e7-82f9-ca2f27de518b.jpg)
![23756035_162008384535900_2000154033_n](https://user-images.githubusercontent.com/10136079/32944678-45584d78-cb88-11e7-89b5-408fd4c46c33.jpg)

**Comment by wolffan** [comment] 2017-11-20 12:06
That is temporary.
Atm we get Coinbase currencies only in $ and then we work out the transform using ticker prices. That's why there's a slight change between our price and Coinbase.

Should be fixed when we pull data in all 3 currencies ($, pound and €)

**Comment by wolffan** [comment] 2017-11-20 12:06
#275 related (I'd say we can close this one)

**Comment by einsteinx2** [comment] 2017-11-20 18:57
@wolffan in Pedro's screenshot, it looks like his ETH balance is actually different. @pedrouid can you confirm that you didn't move money between those screenshots?

**Comment by einsteinx2** [comment] 2017-11-20 18:57
Otherwise agreed that pulling more prices into the backend will help. We should do that for all of the sources now that we've implemented the conversion process differently.

**Comment by einsteinx2** [comment] 2017-11-27 14:07
Closing as dupe of Coinbase balances not updating #231

**Closed by einsteinx2** 2017-11-27 14:07 UTC
