### ISSUE TITLE
Crash due to force unwrapping database password in Database.create() line 73 in beta v0.9.7

### ISSUE THREAD

**Issue by jawiv** [balancemymoney/balance-open#307] opened 2017-11-27 17:06 UTC
**What is the current behaviour?**

Opening the app on my iMac, it crashes immediately. I had an older version of the app with several accounts already linked. I updated to 0.9.7 and the application crashes immediately when I launch it. Knowing this, I opened the older version of BalanceOpen that I had on my Macbook Pro and deleted all the accounts I had linked, then installed 0.9.7. The application loaded fine, but after adding an account or two, it crashed. It does load, but crashes within a minute.

I have linked Coinbase, GDAX, Kraken and Bitfinex on my iMac (to the older version), and Coinbase, GDAX and Kraken to the version I'm running on my Macbook Pro.

**If the current behavior is a bug, please provide the steps to reproduce starting from "launch Balance". If possible, please include a screenshot or a video.**

On iMac, launch application -> immediate crash. Will send bug report when I get home.
On Macbook Pro, launch application -> crash after a few minutes. Sent bug report.

**What is the expected behavior?**

Launch application, program does not crash.

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**

0.9.7. It worked with previous versions, but I'm not sure what versions they were since they've been overwritten.

**Comment by einsteinx2** [comment] 2017-11-29 13:24
Thanks for this report! I'm looking into the crash logs now. Any crash happening immediately on launch will not be reported, but the others will. I currently see distinct 2 crashes for that build, which I'm investigating now.

On the iMac, can you browse to ~/Library/Logs/DiagnosticReports/ and make a zip file of any Balance crashes and add them to this ticket? They may be the same as the ones that were successfully reported, but maybe not. Thanks!

**Comment by einsteinx2** [comment] 2017-11-29 13:48
I have a feeling that we do in fact have crash logs for the crash on launch bug, as we have 4 crash reports all from macOS 10.13.1 systems in the database create function (which would happen right on launch).

Then we have a second set of crashes related to Kraken syncing.

I'm working on resolving both of them now.

**Comment by einsteinx2** [comment] 2017-11-29 13:55
Regarding the crash on launch, assuming you have the same issue as the reported crash logs, it looks like somehow the system is trying to use the stock system-supplied sqlite framework instead of using the sqlcipher version of sqlite that we bundle with the app to allow for encrypting the database. The line that is crashing is the query that unlocks the database and it's crashing on illegal instruction, so it sounds like the stock sqlite doesn't know how to handle that query.

The weird part about that is that we don't link against sqlite at all since we bundle our own version, so there's no reason this should be happening. The fact that all systems reporting this issue are on 10.13.1 leads me to believe there is some macOS bug afoot here that we'll need to work around. However I'm on 10.13.1 and am not experiencing this issue, so it must not be universal.

@jawiv Can you confirm the macOS version on your iMac?

**Comment by einsteinx2** [comment] 2017-11-29 13:58
Actually that may be a red herring as the other crash logs where database create was successful also appear to link to the system sqlite, so potentially that just shows up in all crash logs regardless. In any case, since the past beta, I've rebuilt sqlcipher, so it's possible that fixed whatever is causing this crash

**Comment by einsteinx2** [comment] 2017-11-29 14:03
Looking at the Kraken sync crash, it looks like I fixed that about 3 days after the last beta release (not having realized yet that it was actually causing crashes, just that it had the potential to). We'll be releasing another beta this week which will hopefully resolve both issues. If the crash on launch still occurs with 0.9.8, please reach out to me via Facebook, Slack, or email me at ben [at] balancemy (dot) money so we can take a deeper look. The crash logs give very little to go off of.

As I believe it's likely both crashes are fixed, I'm closing this ticket for now. I'll make a new one for the crash on launch if it still occurs with the next beta.

**Comment by einsteinx2** [comment] 2017-11-29 14:14
Actually I'm re-opening this as I think it may be related to this issue: #277

Swift crash logs can be incredibly misleading as to the actual issue. I notice on that line that we are force unwrapping the database password because it should be impossible for it to be nil...unless it failed to read from the keychain.

Not sure why this would have started happening in 0.9.7 specifically, but it's very possible that this is the cause rather than an sqlcipher issue.

**Comment by einsteinx2** [comment] 2017-11-29 14:25
Actually I'm almost certain that the crash on launch is due to not reading the password from the Keychain.

The other crashes were all related to force unwrapping values when parsing Kraken transactions. They also have a crash type of SIGILL (illegal instruction). Swift should really be reporting something more specific indicating a null pointer access (which is basically what force unwrapping is, though maybe not under the hood), but it doesn't at the moment.

Now the question remains why some machines experience this keychain issue while most don't, but at least I know where to look now.

**Comment by jawiv** [comment] 2017-11-29 16:43
Here is the crash logs from my iMac. Sorry for the delayed response.

I'm running MacOS version 10.13.1 (17B1002)
[crashes.zip](https://github.com/balancemymoney/balance-open/files/1514626/crashes.zip)

**Comment by einsteinx2** [comment] 2017-12-01 14:06
@jawiv Thanks! It looks like your crash on launch and crash later issues are both exactly the same, KrakenTransaction bug that has been fixed. Not quite sure why it's crashing earlier on one machine than the other, as both should sync immediately on launch. Could simply be the order the accounts are syncing. In any case, this is fixed and will be working in the beta I'm trying to get posted today or tomorrow.

**Closed by einsteinx2** 2017-12-01 14:07 UTC
Labels: 1 - Ready, bug
