### ISSUE TITLE
App height is incorrect on a fresh open

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#104] opened 2017-08-30 12:58 UTC
**Problem:**

When I first open the app after starting it from fresh, the app heigh is incorrect. See this screenshot below:

![Screen Shot 2017-08-30 at 13.52.07.png](https://shipusercontent.com/8b33e1f6bbe98fb3af785e522dd13c4a/Screen%20Shot%202017-08-30%20at%2013.52.07.png)

**Expectation:**
The app should be full height when it launches.

**Comment by einsteinx2** [comment] 2017-08-30 17:40
Why should the app be full height? We specifically have logic to adjust the height to match the number of accounts and have always been doing that in Balance.

**Comment by ricburton** [comment] 2017-08-31 09:36
It's too squashed and requires scrolling on launch. It also adjusts in a really jagged way.

On the next launch it's much nicer :)

**Comment by einsteinx2** [comment] 2017-09-11 21:14
Ironically it was actually a bug on the next launch preventing it from resizing correctly.

**Comment by einsteinx2** [comment] 2017-09-11 23:36
Let's define a spec for how we want height, as of right now this is not actionable.

**Comment by wolffan** [comment] 2017-09-22 09:18
Can we revisit or remoe @einsteinx2 @ricburton ?

**Comment by einsteinx2** [comment] 2017-09-28 20:57
Moving to 1.0.1

**Comment by ricburton** [comment] 2017-11-15 14:03
I am seeing lots of issues where the height is wrong when switching from different states. Should I report all of the instances where this happens or are the layout rules being updated? I remember we talked about this before.

**Comment by einsteinx2** [comment] 2017-11-20 19:55
@ricburton we should discuss what we want the final behavior to be. In the meantime, can you create one issue (or add to this one) with all of the specific cases of broken heights you've found? Part of the problem is the hacky way we have to do it, which can potentially be improved.

**Comment by einsteinx2** [comment] 2018-02-09 21:31
I fixed a bunch of resizing issues. Closing this for now as the current design spec specifies to match the account height and Chris D even opened a bug specifically because it _wasn't_ doing this haha. Please discuss with Christian what you guys want the final behavior to be.

**Closed by einsteinx2** 2018-02-09 21:31 UTC
Labels: 0 - Backlog, bug
