### ISSUE TITLE
Unable to create the login item

### ISSUE THREAD

**Issue by balancedcharlie** [balancemymoney/balance-open#112] opened 2017-09-05 11:19 UTC
<img width="557" alt="screenshot 2017-09-05 13 14 49" src="https://user-images.githubusercontent.com/29912727/30058807-cebbe4d8-923c-11e7-9007-0040e42d6dd9.png">

**Comment by einsteinx2** [comment] 2017-09-12 15:43
Looks like there's a general issue with autolaunch. Closing this ticket as dupe of Fix login item add/remove #105 to consolidate.

**Closed by einsteinx2** 2017-09-12 15:43 UTC
Labels: bug
